-- INITCAP() 함수

-- #4101
SELECT INITCAP('pretty girl') 
FROM DUAL ;

-- #4102
SELECT id, INITCAP(ID) "ID"
FROM T_STUDENT 
WHERE DEPTNO1 =201;

-- LOWER(), UPPER()
-- #4103
SELECT NAME "이름",ID "ID", LOWER(ID) 소문자, UPPER(ID) 대문자 
FROM T_STUDENT 
WHERE DEPTNO1 =201;

--LENGTH(), LENGTHB()
-- #4104
SELECT NAME 이름, ID "ID", LENGTH(ID) 글자수
FROM T_STUDENT 
WHERE LENGTH(ID)>=9;

-- #4105
SELECT NAME 이름 ,LENGTH(NAME) 길이, LENGTHB(NAME) 바이트 
FROM T_STUDENT 
WHERE DEPTNO1=201;

--CONCAT()
-- #4106
SELECT CONCAT(name,"POSITION") 교수님명단 
FROM T_PROFESSOR 
WHERE DEPTNO =101;

--SUBSTR
-- #4107
SELECT NAME "NAME", SUBSTR(JUMIN,1,6) 생년월일
FROM T_STUDENT 
WHERE DEPTNO1 =101;

-- #4108
SELECT NAME "NAME", SUBSTR(JUMIN,1,6) 생년월일
FROM T_STUDENT 
WHERE SUBSTR(JUMIN,3,2)='08'; 

-- #4109
SELECT NAME "NAME", JUMIN "JUMIN"
FROM T_STUDENT 
WHERE GRADE=4 AND SUBSTR(JUMIN,7,1)='2';


-- INSTR ('문자열', '문자' , 몇번째 )


-- #4110
SELECT NAME , TEL , INSTR(TEL ,')',1,1) 위치
FROM T_STUDENT 
WHERE DEPTNO1 =101

-- #4111
SELECT NAME ,TEL , SUBSTR(TEL ,1,INSTR(tel,')',1,1)-1) 지역번호
FROM T_STUDENT 
WHERE DEPTNO1 =101

--LTRIM, RTRIM, TRIM
SELECT 
LTRIM('슈퍼슈퍼슈가맨','슈퍼') LTRIM,
LTRIM('슈퍼슈퍼슈가맨','슈') LTRIM,
LTRIM('  슈퍼슈퍼슈가맨',' ') LTRIM,
RTRIM('  슈퍼슈퍼슈가맨      ',' ') RTRIM,
TRIM('  슈퍼슈퍼슈가맨      ') TRIM,
RTRIM('  슈퍼슈퍼슈가맨      ') RTRIM
FROM DUAL ;

-- #4117
SELECT RTRIM(DNAME ,'부') RTRIM예제 
FROM t_dept2


-- REPLACE
SELECT REPLACE ('슈퍼맨 슈퍼걸','슈퍼','파워')
FROM dual;

-- #4118
SELECT REPLACE(name,SUBSTR(name,1,1),'#') 
FROM T_STUDENT 
WHERE DEPTNO1 = 102;

-- #4119
SELECT REPLACE(name ,SUBSTR(name,2,1),'#') 학생
FROM T_STUDENT 
WHERE DEPTNO1 =101;

-- #4120
SELECT NAME ,REPLACE(JUMIN, SUBSTR(JUMIN ,7,7),'*******' )
FROM T_STUDENT 
WHERE DEPTNO1 =101;

-- #4121
SELECT NAME, TEL, REPLACE(tel ,SUBSTR(TEL ,INSTR(TEL ,')',1)+1,3),'###') 전화번호
FROM T_STUDENT 
WHERE DEPTNO1 =102;