SELECT *
FROM t_gift;

SELECT *
FROM T_CUSTOMER ;

--#6201
SELECT c.C_NAME 고객명,c.C_POINT POINT, g.G_NAME 상품명
FROM T_GIFT g,T_CUSTOMER c
WHERE c.C_POINT BETWEEN g.G_START AND G_END ;

SELECT c.C_NAME 고객명,c.C_POINT POINT, g.G_NAME 상품명
FROM T_GIFT g join T_CUSTOMER c
on c.C_POINT BETWEEN g.G_START AND G_END

--#6202
SELECT g.G_NAME 상품명 ,COUNT(g.G_NAME) 필요수량
FROM T_GIFT g join T_CUSTOMER c
on c.C_POINT BETWEEN g.G_START AND G_END
GROUP BY g.G_NAME;


--#6203
SELECT s.NAME ,e.TOTAL ,c.GRADE 
FROM T_STUDENT s, T_EXAM01 e,T_CREDIT c
WHERE e.STUDNO =s.STUDNO AND e.TOTAL BETWEEN c.MIN_POINT AND c.MAX_POINT 
ORDER BY e.TOTAL DESC;

SELECT s.NAME ,e.TOTAL ,c.GRADE 
FROM T_STUDENT s 
JOIN T_EXAM01 e ON e.STUDNO =s.STUDNO 
JOIN T_CREDIT c on e.TOTAL BETWEEN c.MIN_POINT AND c.MAX_POINT 
ORDER BY e.TOTAL DESC;

--#6204
SELECT c.C_NAME 고객명,c.C_POINT POINT, g.G_NAME 상품명 
FROM T_CUSTOMER c,T_GIFT g
WHERE c.C_POINT >g.G_START AND g.G_NAME ='산악용자전거';

SELECT c.C_NAME 고객명,c.C_POINT POINT, g.G_NAME 상품명 
FROM T_CUSTOMER c JOIN T_GIFT g
ON c.C_POINT >g.G_START AND g.G_NAME ='산악용자전거';

--#6205
SELECT e.NAME 이름, TruNC(MONTHS_BETWEEN(SYSDATE,e.BIRTHDAY)/12) 현재나이 ,NVL(e.POST,' ') 현재직급,p.POST 예상직급
FROM T_EMP2 e, T_POST p
WHERE  TruNC(MONTHS_BETWEEN(SYSDATE,e.BIRTHDAY)/12) BETWEEN p.S_AGE AND p.E_AGE 
;

SELECT e.NAME 이름, (TO_CHAR(sysdate,'YYYY')-TO_CHAR(e.BIRTHDAY ,'YYYY')+1) 현재나이 ,NVL(e.POST,' ') 현재직급,p.POST 예상직급
FROM T_EMP2 e join T_POST p
ON  (TO_CHAR(sysdate,'YYYY')-TO_CHAR(e.BIRTHDAY ,'YYYY')+1) BETWEEN p.S_AGE AND p.E_AGE 
;

--#6206
SELECT s.NAME ,p.NAME 
FROM T_STUDENT s LEFT OUTER JOIN T_PROFESSOR p
ON s.PROFNO =p.PROFNO ;


SELECT s.NAME ,p.NAME 
FROM T_STUDENT s RIGHT OUTER JOIN T_PROFESSOR p
ON s.PROFNO =p.PROFNO ;

SELECT s.NAME ,p.NAME 
FROM T_STUDENT s FULL OUTER JOIN T_PROFESSOR p
ON s.PROFNO =p.PROFNO ;

--#6209
SELECT d1.DNAME 부서명 ,d2.DNAME 상위부서명
FROM T_DEPT2 d1,T_DEPT2 d2 
WHERE d1.PDEPT =d2.DCODE ;

SELECT d1.DNAME 부서명 ,d2.DNAME 상위부서명
FROM T_DEPT2 d1 JOIN T_DEPT2 d2 
ON d1.PDEPT =d2.DCODE ;

--#6210
SELECT p1.DEPTNO 교수번호,p1.NAME 교수명 ,p1.HIREDATE 입사일 ,count(p2.HIREDATE) 빠른사람
FROM T_PROFESSOR p1 LEFT OUTER join T_PROFESSOR p2
ON p1.HIREDATE >p2.HIREDATE
GROUP BY 
p1.DEPTNO,p1.NAME ,p1.HIREDATE 
ORDER BY count(p2.HIREDATE) ASC
;

